"""Initial migration

Revision ID: a4d6c01aa9ff
Revises: 
Create Date: 2026-02-19 14:31:06.500663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d6c01aa9ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('article_id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_articles_published_at'), 'articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_articles_title'), 'articles', ['title'], unique=False)
    op.create_table('sentiment_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('avg_sentiment', sa.Float(), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('momentum', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='unique_ticker_date')
    )
    op.create_index(op.f('ix_sentiment_daily_date'), 'sentiment_daily', ['date'], unique=False)
    op.create_index(op.f('ix_sentiment_daily_ticker'), 'sentiment_daily', ['ticker'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('article_entities',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], ),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_index(op.f('ix_article_entities_article_id'), 'article_entities', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_entities_ticker'), 'article_entities', ['ticker'], unique=False)
    op.create_table('portfolios',
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('portfolio_id')
    )
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('trigger_reason', sa.String(), nullable=False),
    sa.Column('sentiment_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_ticker'), 'alerts', ['ticker'], unique=False)
    op.create_table('portfolio_tickers',
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.portfolio_id'], ),
    sa.PrimaryKeyConstraint('ticker_id')
    )
    op.create_index(op.f('ix_portfolio_tickers_portfolio_id'), 'portfolio_tickers', ['portfolio_id'], unique=True)
    op.create_index(op.f('ix_portfolio_tickers_ticker'), 'portfolio_tickers', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_tickers_ticker'), table_name='portfolio_tickers')
    op.drop_index(op.f('ix_portfolio_tickers_portfolio_id'), table_name='portfolio_tickers')
    op.drop_table('portfolio_tickers')
    op.drop_index(op.f('ix_alerts_ticker'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_article_entities_ticker'), table_name='article_entities')
    op.drop_index(op.f('ix_article_entities_article_id'), table_name='article_entities')
    op.drop_table('article_entities')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sentiment_daily_ticker'), table_name='sentiment_daily')
    op.drop_index(op.f('ix_sentiment_daily_date'), table_name='sentiment_daily')
    op.drop_table('sentiment_daily')
    op.drop_index(op.f('ix_articles_title'), table_name='articles')
    op.drop_index(op.f('ix_articles_published_at'), table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
